INSERT INTO "DobradaPauloAlexandreLeader" (
    "id",
    "fullName",
    "source",
    "notes",
    "status",
    "createdAt",
    "updatedAt"
) VALUES
    ('dobrada-paulo-alexandre-adilson-farmacia', 'Adilson da Farmácia', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-joelio', 'Joélio', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-fabio-moura', 'Fábio Moura', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-negretta', 'Negretta (Cons.)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-tia-lu', 'Tia Lú (Cons.)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-fernanda-barbosa', 'Fernanda Barbosa (Cons.)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-jackson', 'Jackson (Felipe/Silvia/Valéria)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-bira', 'Bira', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-gordao', 'Gordão', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-boteco', 'Boteco', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-mancusi', 'Mancusi', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-pan', 'Pan', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-dengoso', 'Dengoso', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-tia-valdenice', 'Tia Valdenice (Quadrilhas Juninas)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-paulo-feliciano', 'Paulo Feliciano', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-nado', 'Nado (Associação)', 'Carga inicial Dobrada Paulo Alexandre', 'Boby (40)', 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-michel-tiziane', 'Michel Tiziane (Filetti)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-bicudo', 'Bicudo', 'Carga inicial Dobrada Paulo Alexandre', 'Substitui Pati Bora La, que estava riscado.', 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-clemir', 'Clemir', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-leticia-silva', 'Letícia Silva (Cons.)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-equipe-dobrada', 'Equipe Dobrada', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-ezinho', 'Ezinho', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-higor-cufa', 'Higor (CUFA)', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW()),
    ('dobrada-paulo-alexandre-trindade', 'Trindade', 'Carga inicial Dobrada Paulo Alexandre', NULL, 'ACTIVE', NOW(), NOW())
ON CONFLICT ("id") DO UPDATE SET
    "fullName" = EXCLUDED."fullName",
    "source" = EXCLUDED."source",
    "notes" = EXCLUDED."notes",
    "status" = EXCLUDED."status",
    "updatedAt" = NOW();
